import Link from "next/link";
import { ArrowRight, BadgeCheck, Building2, Check, CircleCheck, Factory, Headphones, Home, LandPlot, PlugZap, Settings2, ShieldCheck, Store, Wrench } from "lucide-react";
import { HeroIllustration } from "@/components/HeroIllustration";
import { ServiceCard } from "@/components/ServiceCard";
import { SectionHeading } from "@/components/SectionHeading";
import { ProjectCard } from "@/components/ProjectCard";
import { FAQAccordion } from "@/components/FAQAccordion";
import { CTASection } from "@/components/CTASection";
import { services } from "@/data/services";
import { projects } from "@/data/projects";
import { pageMetadata } from "@/lib/metadata";
export const metadata=pageMetadata("Micronativa | Energia Solar, CFTV e Automação","Projetos e instalações de energia solar, câmeras de segurança, controle de acesso e automação de portões para residências e empresas.");
const trust=[["Projetos personalizados","Dimensionamento para cada necessidade",Settings2],["Instalação profissional","Execução técnica e organizada",Wrench],["Equipamentos de qualidade","Seleção adequada a cada projeto",BadgeCheck],["Suporte especializado","Orientação antes e depois da instalação",Headphones]];
const segments=[["Residências","Conforto, proteção e economia no dia a dia.",Home],["Comércios","Monitoramento e acessos mais organizados.",Store],["Empresas","Infraestrutura integrada e escalável.",Building2],["Condomínios","Controle de moradores, visitantes e áreas comuns.",ShieldCheck],["Indústrias","Continuidade, visibilidade e eficiência.",Factory],["Propriedades rurais","Soluções adaptadas a áreas amplas e remotas.",LandPlot]];
const steps=["Primeiro contato","Levantamento das necessidades","Visita técnica","Proposta personalizada","Instalação e configuração","Testes e suporte"];
const benefits=["Atendimento técnico","Projetos personalizados","Instalação organizada","Equipamentos confiáveis","Integração entre soluções","Suporte pós-instalação","Manutenção preventiva","Comunicação transparente"];
const faqs=[
{question:"A energia solar funciona em dias nublados?",answer:"Sim. A geração pode ser menor conforme a radiação disponível, mas o sistema continua produzindo. O projeto considera as condições locais e o histórico de consumo."},
{question:"Posso acessar as câmeras pelo celular?",answer:"Quando o projeto prevê acesso remoto e há conexão adequada, o sistema pode ser configurado para visualização autorizada pelo celular."},
{question:"Vocês automatizam portões já instalados?",answer:"Sim, após uma avaliação da estrutura, do peso, do movimento e dos dispositivos de segurança necessários."},
{question:"Quais tipos de controle de acesso vocês instalam?",answer:"Tags, cartões, biometria, senhas, fechaduras eletrônicas, vídeo porteiros e outras opções definidas conforme o fluxo do local."},
{question:"A empresa realiza manutenção?",answer:"A Micronativa pode avaliar sistemas instalados e propor manutenção preventiva ou corretiva conforme o diagnóstico técnico."},
{question:"Quais regiões são atendidas?",answer:"A área de atendimento será confirmada conforme a cidade do projeto. Envie sua localização pelo formulário para validação."},
{question:"Como solicitar um orçamento?",answer:"Preencha o formulário em etapas ou fale pelo WhatsApp. Quanto mais contexto você enviar, mais objetiva será a primeira avaliação."},
{question:"É necessário realizar uma visita técnica?",answer:"Depende do serviço e do imóvel. Alguns projetos exigem levantamento presencial antes da proposta definitiva."}
];
export default function HomePage(){return <>
<section className="relative overflow-hidden"><div className="absolute inset-y-0 right-0 hidden w-1/2 bg-forest-pale/60 lg:block"/><div className="container-site grid items-center gap-12 py-14 sm:py-20 lg:grid-cols-[.92fr_1.08fr] lg:py-24"><div className="relative z-10"><p className="eyebrow"><PlugZap className="size-4"/>Soluções integradas para residências e empresas</p><h1 className="display-title mt-5">Tecnologia para <span className="text-forest">economizar</span>, proteger e automatizar seu imóvel.</h1><p className="body-large mt-6 max-w-2xl">Projetos e instalações de energia solar, CFTV, controle de acesso e automação de portões para residências, empresas, condomínios e propriedades rurais.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/orcamento?source=home" className="btn-primary">Solicitar orçamento <ArrowRight className="size-4"/></Link><Link href="/solucoes" className="btn-secondary">Conhecer soluções</Link></div><p className="mt-6 flex items-start gap-2 text-sm font-semibold text-muted"><CircleCheck className="mt-0.5 size-5 shrink-0 text-forest"/>Atendimento técnico, projeto personalizado e suporte especializado.</p></div><HeroIllustration/></div></section>
<section className="border-y bg-white"><div className="container-site grid md:grid-cols-2 xl:grid-cols-4">{trust.map(([title,text,Icon])=><div key={title as string} className="flex gap-4 border-navy/10 px-5 py-7 xl:border-l first:xl:border-l-0"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-warm text-forest"><Icon className="size-5"/></span><div><h2 className="font-bold">{title as string}</h2><p className="mt-1 text-sm leading-6 text-muted">{text as string}</p></div></div>)}</div></section>
<section className="section-pad"><div className="container-site"><SectionHeading eyebrow="Nossas soluções" title="Soluções para tornar seu imóvel mais eficiente e seguro" description="Tecnologias selecionadas e instaladas de acordo com o uso, a infraestrutura e os objetivos de cada cliente."/><div className="mt-10 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{services.map(s=><ServiceCard key={s.slug} service={s}/>)}</div></div></section>
<section className="section-pad bg-navy text-white"><div className="container-site grid items-center gap-12 lg:grid-cols-[.85fr_1.15fr]"><div><p className="eyebrow !text-solar">Visão integrada</p><h2 className="section-title mt-4">Um único parceiro para energia, segurança e automação</h2><p className="mt-6 text-lg leading-8 text-white/70">Desenvolvemos projetos independentes ou integrados, permitindo que diferentes tecnologias funcionem de maneira organizada no mesmo imóvel.</p><div className="mt-7 flex flex-wrap gap-2">{services.map(s=><span key={s.slug} className="rounded-full border border-white/15 bg-white/5 px-4 py-2 text-sm font-bold text-white/80">{s.title}</span>)}</div><Link href="/orcamento?service=projeto-integrado&source=home" className="btn mt-8 bg-solar text-ink hover:bg-white">Planejar meu projeto <ArrowRight className="size-4"/></Link></div><figure className="group overflow-hidden rounded-4xl border border-white/10 bg-[#071b38] shadow-2xl"><img src="/images/isometric/integrated.webp" alt="Miniatura isométrica de projeto integrado de energia, segurança e automação" className="aspect-square h-full w-full object-cover transition duration-700 group-hover:scale-[1.02]" loading="lazy" decoding="async"/></figure></div></section>
<section className="section-pad"><div className="container-site"><SectionHeading eyebrow="Perfis atendidos" title="Soluções para diferentes tipos de projeto"/><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{segments.map(([title,text,Icon])=><article key={title as string} className="card p-6"><Icon className="size-7 text-forest"/><h3 className="mt-4 text-xl font-bold">{title as string}</h3><p className="mt-2 leading-7 text-muted">{text as string}</p></article>)}</div></div></section>
<section className="section-pad bg-white"><div className="container-site"><SectionHeading eyebrow="Nosso processo" title="Como funciona o atendimento" description="Um fluxo claro para transformar necessidades em uma solução bem dimensionada."/><div className="mt-12 grid items-stretch gap-8 lg:grid-cols-[1.2fr_.8fr]"><figure className="group min-h-96 overflow-hidden rounded-4xl border bg-forest-pale shadow-soft"><img src="/images/isometric/process.webp" alt="Jornada isométrica do atendimento técnico, do primeiro contato à instalação concluída" className="h-full min-h-96 w-full object-cover transition duration-700 group-hover:scale-[1.02]" loading="lazy" decoding="async"/></figure><ol className="grid gap-3 sm:grid-cols-2 lg:grid-cols-1">{steps.map((step,i)=><li key={step} className="flex items-center gap-4 rounded-2xl border bg-warm p-4 shadow-sm"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-forest font-extrabold text-white">{String(i+1).padStart(2,"0")}</span><h3 className="font-bold leading-6">{step}</h3></li>)}</ol></div></div></section>
<section className="section-pad"><div className="container-site grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><SectionHeading eyebrow="Compromisso técnico" title="Por que escolher a Micronativa?" description="Planejamento, execução e suporte tratados como partes do mesmo projeto."/><div className="grid gap-3 sm:grid-cols-2">{benefits.map(b=><div key={b} className="flex items-center gap-3 rounded-2xl border bg-white p-4 font-semibold"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-forest-pale"><Check className="size-4 text-forest"/></span>{b}</div>)}</div></div></section>
<section className="section-pad bg-white"><div className="container-site"><div className="flex flex-col gap-6 sm:flex-row sm:items-end sm:justify-between"><SectionHeading eyebrow="Portfólio" title="Projetos e estudos de caso" description="Conteúdos demonstrativos prontos para receber registros reais e autorizados."/><Link href="/projetos" className="btn-secondary">Ver todos os projetos</Link></div><div className="mt-10 grid gap-6 md:grid-cols-2 xl:grid-cols-3">{projects.filter(p=>p.featured).slice(0,3).map(p=><ProjectCard key={p.id} project={p}/>)}</div></div></section>
<section className="section-pad"><div className="container-site grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["+000","projetos concluídos"],["+00","cidades atendidas"],["00","anos de experiência"],["Atendimento","especializado"]].map(([v,l])=><div key={l} className="rounded-3xl bg-forest-dark p-7 text-white"><p className="text-4xl font-extrabold text-solar">{v}</p><p className="mt-2 text-sm text-white/70">{l} — dado a substituir</p></div>)}</div></section>
<section className="section-pad bg-forest-pale/50"><div className="container-site"><SectionHeading align="center" eyebrow="Atendimento" title="Confiança construída em cada etapa" description="Depoimentos demonstrativos — substituir por relatos reais autorizados."/><div className="mt-10 grid gap-5 lg:grid-cols-3">{["O atendimento foi claro desde a primeira conversa, com explicações sobre cada etapa do projeto.","A equipe organizou a instalação e nos orientou sobre o uso do sistema.","Conseguimos avaliar diferentes soluções e escolher o que fazia sentido para o imóvel."].map((t,i)=><blockquote key={i} className="card p-7"><p className="leading-8 text-ink">“{t}”</p><footer className="mt-6 text-sm font-bold text-muted">Cliente demonstrativo — substituir</footer></blockquote>)}</div></div></section>
<section className="section-pad bg-white"><div className="container-site"><SectionHeading align="center" eyebrow="Dúvidas frequentes" title="Respostas para começar seu projeto"/><div className="mt-10"><FAQAccordion items={faqs}/></div></div></section>
<CTASection/>
</>}
