import Link from "next/link";
import { ArrowRight, BadgeCheck, Building2, Check, CircleCheck, Factory, Headphones, Home, LandPlot, PlugZap, Settings2, ShieldCheck, Store, Wrench } from "lucide-react";
import { HeroIllustration } from "@/components/HeroIllustration";
import { ServiceCard } from "@/components/ServiceCard";
import { SectionHeading } from "@/components/SectionHeading";
import { ProjectCard } from "@/components/ProjectCard";
import { FAQAccordion } from "@/components/FAQAccordion";
import { CTASection } from "@/components/CTASection";
import { services } from "@/data/services";
import { projects } from "@/data/projects";
import { pageMetadata } from "@/lib/metadata";
export const metadata=pageMetadata("Micronativa | Energia Solar, CFTV e Automa??o","Projetos e instala??es de energia solar, c?meras de seguran?a, controle de acesso e automa??o de port?es para resid?ncias e empresas.");
const trust=[["Projetos personalizados","Dimensionamento para cada necessidade",Settings2],["Instala??o profissional","Execu??o t?cnica e organizada",Wrench],["Equipamentos de qualidade","Sele??o adequada a cada projeto",BadgeCheck],["Suporte especializado","Orienta??o antes e depois da instala??o",Headphones]];
const segments=[["Resid?ncias","Conforto, prote??o e economia no dia a dia.",Home],["Com?rcios","Monitoramento e acessos mais organizados.",Store],["Empresas","Infraestrutura integrada e escal?vel.",Building2],["Condom?nios","Controle de moradores, visitantes e ?reas comuns.",ShieldCheck],["Ind?strias","Continuidade, visibilidade e efici?ncia.",Factory],["Propriedades rurais","Solu??es adaptadas a ?reas amplas e remotas.",LandPlot]];
const steps=["Primeiro contato","Levantamento das necessidades","Visita t?cnica","Proposta personalizada","Instala??o e configura??o","Testes e suporte"];
const benefits=["Atendimento t?cnico","Projetos personalizados","Instala??o organizada","Equipamentos confi?veis","Integra??o entre solu??es","Suporte p?s-instala??o","Manuten??o preventiva","Comunica??o transparente"];
const faqs=[
{question:"A energia solar funciona em dias nublados?",answer:"Sim. A gera??o pode ser menor conforme a radia??o dispon?vel, mas o sistema continua produzindo. O projeto considera as condi??es locais e o hist?rico de consumo."},
{question:"Posso acessar as c?meras pelo celular?",answer:"Quando o projeto prev? acesso remoto e h? conex?o adequada, o sistema pode ser configurado para visualiza??o autorizada pelo celular."},
{question:"Voc?s automatizam port?es j? instalados?",answer:"Sim, ap?s uma avalia??o da estrutura, do peso, do movimento e dos dispositivos de seguran?a necess?rios."},
{question:"Quais tipos de controle de acesso voc?s instalam?",answer:"Tags, cart?es, biometria, senhas, fechaduras eletr?nicas, v?deo porteiros e outras op??es definidas conforme o fluxo do local."},
{question:"A empresa realiza manuten??o?",answer:"A Micronativa pode avaliar sistemas instalados e propor manuten??o preventiva ou corretiva conforme o diagn?stico t?cnico."},
{question:"Quais regi?es s?o atendidas?",answer:"A ?rea de atendimento ser? confirmada conforme a cidade do projeto. Envie sua localiza??o pelo formul?rio para valida??o."},
{question:"Como solicitar um or?amento?",answer:"Preencha o formul?rio em etapas ou fale pelo WhatsApp. Quanto mais contexto voc? enviar, mais objetiva ser? a primeira avalia??o."},
{question:"? necess?rio realizar uma visita t?cnica?",answer:"Depende do servi?o e do im?vel. Alguns projetos exigem levantamento presencial antes da proposta definitiva."}
];
export default function HomePage(){return <>
<section className="relative overflow-hidden"><div className="absolute inset-y-0 right-0 hidden w-1/2 bg-forest-pale/60 lg:block"/><div className="container-site grid items-center gap-12 py-14 sm:py-20 lg:grid-cols-[.92fr_1.08fr] lg:py-24"><div className="relative z-10"><p className="eyebrow"><PlugZap className="size-4"/>Solu??es integradas para resid?ncias e empresas</p><h1 className="display-title mt-5">Tecnologia para <span className="text-forest">economizar</span>, proteger e automatizar seu im?vel.</h1><p className="body-large mt-6 max-w-2xl">Projetos e instala??es de energia solar, CFTV, controle de acesso e automa??o de port?es para resid?ncias, empresas, condom?nios e propriedades rurais.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/orcamento?source=home" className="btn-primary">Solicitar or?amento <ArrowRight className="size-4"/></Link><Link href="/solucoes" className="btn-secondary">Conhecer solu??es</Link></div><p className="mt-6 flex items-start gap-2 text-sm font-semibold text-muted"><CircleCheck className="mt-0.5 size-5 shrink-0 text-forest"/>Atendimento t?cnico, projeto personalizado e suporte especializado.</p></div><HeroIllustration/></div></section>
<section className="border-y bg-white"><div className="container-site grid md:grid-cols-2 xl:grid-cols-4">{trust.map(([title,text,Icon])=><div key={title as string} className="flex gap-4 border-navy/10 px-5 py-7 xl:border-l first:xl:border-l-0"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-warm text-forest"><Icon className="size-5"/></span><div><h2 className="font-bold">{title as string}</h2><p className="mt-1 text-sm leading-6 text-muted">{text as string}</p></div></div>)}</div></section>
<section className="section-pad"><div className="container-site"><SectionHeading eyebrow="Nossas solu??es" title="Solu??es para tornar seu im?vel mais eficiente e seguro" description="Tecnologias selecionadas e instaladas de acordo com o uso, a infraestrutura e os objetivos de cada cliente."/><div className="mt-10 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{services.map(s=><ServiceCard key={s.slug} service={s}/>)}</div></div></section>
<section className="section-pad bg-navy text-white"><div className="container-site grid items-center gap-12 lg:grid-cols-2"><div><p className="eyebrow !text-solar">Vis?o integrada</p><h2 className="section-title mt-4">Um ?nico parceiro para energia, seguran?a e automa??o</h2><p className="mt-6 text-lg leading-8 text-white/70">Desenvolvemos projetos independentes ou integrados, permitindo que diferentes tecnologias funcionem de maneira organizada no mesmo im?vel.</p><Link href="/orcamento?service=projeto-integrado&source=home" className="btn mt-8 bg-solar text-ink hover:bg-white">Planejar meu projeto <ArrowRight className="size-4"/></Link></div><div className="grid grid-cols-2 gap-4">{services.map((s,i)=><div key={s.slug} className="rounded-3xl border border-white/10 bg-white/5 p-5"><s.icon className="size-7 text-solar"/><p className="mt-4 font-bold">{s.title}</p><p className="mt-2 text-sm text-white/60">{i===0?"Gera??o":i===1?"Monitoramento":i===2?"Movimento":"Identifica??o"}</p></div>)}</div></div></section>
<section className="section-pad"><div className="container-site"><SectionHeading eyebrow="Perfis atendidos" title="Solu??es para diferentes tipos de projeto"/><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{segments.map(([title,text,Icon])=><article key={title as string} className="card p-6"><Icon className="size-7 text-forest"/><h3 className="mt-4 text-xl font-bold">{title as string}</h3><p className="mt-2 leading-7 text-muted">{text as string}</p></article>)}</div></div></section>
<section className="section-pad bg-white"><div className="container-site"><SectionHeading eyebrow="Nosso processo" title="Como funciona o atendimento" description="Um fluxo claro para transformar necessidades em uma solu??o bem dimensionada."/><ol className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{steps.map((step,i)=><li key={step} className="relative rounded-3xl bg-warm p-6"><span className="text-sm font-extrabold text-forest">0{i+1}</span><h3 className="mt-8 text-lg font-bold">{step}</h3></li>)}</ol></div></section>
<section className="section-pad"><div className="container-site grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><SectionHeading eyebrow="Compromisso t?cnico" title="Por que escolher a Micronativa?" description="Planejamento, execu??o e suporte tratados como partes do mesmo projeto."/><div className="grid gap-3 sm:grid-cols-2">{benefits.map(b=><div key={b} className="flex items-center gap-3 rounded-2xl border bg-white p-4 font-semibold"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-forest-pale"><Check className="size-4 text-forest"/></span>{b}</div>)}</div></div></section>
<section className="section-pad bg-white"><div className="container-site"><div className="flex flex-col gap-6 sm:flex-row sm:items-end sm:justify-between"><SectionHeading eyebrow="Portf?lio" title="Projetos e estudos de caso" description="Conte?dos demonstrativos prontos para receber registros reais e autorizados."/><Link href="/projetos" className="btn-secondary">Ver todos os projetos</Link></div><div className="mt-10 grid gap-6 md:grid-cols-2 xl:grid-cols-3">{projects.filter(p=>p.featured).slice(0,3).map(p=><ProjectCard key={p.id} project={p}/>)}</div></div></section>
<section className="section-pad"><div className="container-site grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["+000","projetos conclu?dos"],["+00","cidades atendidas"],["00","anos de experi?ncia"],["Atendimento","especializado"]].map(([v,l])=><div key={l} className="rounded-3xl bg-forest-dark p-7 text-white"><p className="text-4xl font-extrabold text-solar">{v}</p><p className="mt-2 text-sm text-white/70">{l} ? dado a substituir</p></div>)}</div></section>
<section className="section-pad bg-forest-pale/50"><div className="container-site"><SectionHeading align="center" eyebrow="Atendimento" title="Confian?a constru?da em cada etapa" description="Depoimentos demonstrativos ? substituir por relatos reais autorizados."/><div className="mt-10 grid gap-5 lg:grid-cols-3">{["O atendimento foi claro desde a primeira conversa, com explica??es sobre cada etapa do projeto.","A equipe organizou a instala??o e nos orientou sobre o uso do sistema.","Conseguimos avaliar diferentes solu??es e escolher o que fazia sentido para o im?vel."].map((t,i)=><blockquote key={i} className="card p-7"><p className="leading-8 text-ink">?{t}?</p><footer className="mt-6 text-sm font-bold text-muted">Cliente demonstrativo ? substituir</footer></blockquote>)}</div></div></section>
<section className="section-pad bg-white"><div className="container-site"><SectionHeading align="center" eyebrow="D?vidas frequentes" title="Respostas para come?ar seu projeto"/><div className="mt-10"><FAQAccordion items={faqs}/></div></div></section>
<CTASection/>
</>}
