import Link from "next/link";
import { ArrowRight, Check, CircleDot, ClipboardCheck, Hammer, Search, Settings2 } from "lucide-react";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { SectionHeading } from "@/components/SectionHeading";
import { FAQAccordion } from "@/components/FAQAccordion";
import { CTASection } from "@/components/CTASection";
import { ProjectCard } from "@/components/ProjectCard";
import { projects } from "@/data/projects";
import type { Service } from "@/data/services";
export function ServicePageTemplate({service}:{service:Service}){
 const related=projects.filter(p=>p.category===service.slug).slice(0,3);
 const faq=[{question:"Como saber qual sistema ? adequado?",answer:"A defini??o depende do objetivo, da infraestrutura e do uso do im?vel. O levantamento t?cnico ajuda a dimensionar a solu??o."},{question:"? necess?rio fazer uma visita t?cnica?",answer:"Em muitos casos, sim. A visita confirma medidas, infraestrutura, acesso, condi??es de instala??o e equipamentos necess?rios."},{question:"Voc?s realizam manuten??o?",answer:"Sim. A equipe pode avaliar o sistema e indicar a manuten??o adequada conforme o diagn?stico."}];
 return <><section className="overflow-hidden bg-white"><div className="container-site py-10"><Breadcrumbs items={[{label:"Solu??es",href:"/solucoes"},{label:service.title}]}/><div className="grid items-center gap-12 py-12 lg:grid-cols-[1.05fr_.95fr]"><div><p className="eyebrow">{service.eyebrow}</p><h1 className="display-title mt-5">{service.heading}</h1><p className="body-large mt-6">{service.description}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link className="btn-primary" href={"/orcamento?service="+service.slug+"&source=service"}>Solicitar avalia??o <ArrowRight className="size-4"/></Link><Link className="btn-secondary" href="#como-funciona">Como funciona</Link></div></div><div className="grid-pattern relative min-h-96 overflow-hidden rounded-4xl bg-forest-pale p-8"><div className="absolute -right-12 -top-12 size-48 rounded-full bg-solar/50"/><div className="relative flex h-full min-h-80 flex-col justify-between rounded-3xl border border-white bg-white/85 p-7 shadow-soft"><span className="grid size-16 place-items-center rounded-2xl bg-navy text-white"><service.icon className="size-8"/></span><div><p className="text-sm font-bold uppercase tracking-wider text-forest">Projeto sob medida</p><h2 className="mt-2 text-3xl font-bold">Da avalia??o ao suporte.</h2><p className="mt-3 leading-7 text-muted">Decis?es t?cnicas documentadas e uma instala??o alinhada ao uso real do im?vel.</p></div></div></div></div></div></section>
 <section className="section-pad"><div className="container-site"><SectionHeading eyebrow="Principais benef?cios" title="Tecnologia bem aplicada ao seu dia a dia"/><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{service.benefits.map(b=><article key={b} className="card p-6"><Check className="size-6 text-forest"/><h3 className="mt-5 font-bold">{b}</h3></article>)}</div></div></section>
 <section className="section-pad bg-navy text-white"><div className="container-site grid gap-10 lg:grid-cols-2"><div><SectionHeading eyebrow="Diagn?stico" title="Problemas que esta solu??o ajuda a resolver"/><ul className="mt-8 grid gap-3">{service.solves.map(x=><li key={x} className="flex gap-3 rounded-2xl bg-white/5 p-4"><CircleDot className="size-5 shrink-0 text-solar"/>{x}</li>)}</ul></div><div><h2 className="text-2xl font-bold">Sistemas e possibilidades</h2><ul className="mt-8 grid gap-3 sm:grid-cols-2">{service.systems.map(x=><li key={x} className="flex items-center gap-3 border-b border-white/10 pb-3 text-white/75"><Check className="size-4 shrink-0 text-solar"/>{x}</li>)}</ul></div></div></section>
 <section className="section-pad"><div className="container-site"><SectionHeading eyebrow="Aplica??es" title="Projetos para diferentes perfis"/><div className="mt-10 flex flex-wrap gap-3">{service.segments.map(s=><span key={s} className="rounded-full border bg-white px-5 py-3 font-bold text-navy">{s}</span>)}</div></div></section>
 <section id="como-funciona" className="section-pad bg-white"><div className="container-site"><SectionHeading eyebrow="Execu??o" title="Como conduzimos a instala??o"/><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{[[Search,"Levantamento","Entendemos o im?vel e a necessidade."],[ClipboardCheck,"Projeto","Definimos escopo e componentes."],[Hammer,"Instala??o","Executamos com organiza??o t?cnica."],[Settings2,"Testes e suporte","Configuramos, testamos e orientamos."]].map(([Icon,t,d])=><article key={t as string} className="rounded-3xl bg-warm p-6"><Icon className="size-7 text-forest"/><h3 className="mt-5 text-lg font-bold">{t as string}</h3><p className="mt-2 text-sm leading-6 text-muted">{d as string}</p></article>)}</div></div></section>
 {related.length>0&&<section className="section-pad"><div className="container-site"><SectionHeading eyebrow="Portf?lio" title="Projetos relacionados"/><div className="mt-10 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{related.map(p=><ProjectCard key={p.id} project={p}/>)}</div></div></section>}
 <section className="section-pad bg-white"><div className="container-site"><SectionHeading align="center" eyebrow="D?vidas" title={"Perguntas sobre "+service.title}/><div className="mt-10"><FAQAccordion items={faq}/></div></div></section>
 <CTASection context={service.whatsappContext} service={service.slug}/></>;
}
