import Link from "next/link";
import { Facebook, Instagram, Linkedin, Mail, MapPin, Phone } from "lucide-react";
import { company } from "@/config/company";
import { WhatsAppButton } from "@/components/WhatsAppButton";

export function SiteFooter() {
  return <footer className="bg-navy text-white"><div className="container-site grid gap-12 py-16 lg:grid-cols-[1.2fr_.8fr_1fr]"><div><Link href="/" className="inline-flex items-center gap-3"><img src="/images/brand/micronativa-logo-transparent.png" alt="" className="size-14 object-contain drop-shadow-md" /><span className="font-extrabold tracking-wide">MICRONATIVA</span></Link><p className="mt-5 max-w-md text-sm leading-7 text-white/70">Soluções integradas em energia solar, segurança eletrônica, automação e controle de acesso no Paraná e em Santa Catarina.</p><WhatsAppButton context="home" variant="secondary" label="Chamar no WhatsApp" className="mt-6 border-white/20 bg-white/10 text-white hover:bg-white hover:text-forest" /></div>
    <div><h2 className="font-bold">Navegação</h2><ul className="mt-4 space-y-3 text-sm text-white/70"><li><Link href="/sobre" className="hover:text-white">Sobre a empresa</Link></li><li><Link href="/contato" className="hover:text-white">Contato</Link></li><li><Link href="/consultar-protocolo" className="hover:text-white">Acompanhar solicitação</Link></li><li><Link href="/politica-de-privacidade" className="hover:text-white">Política de Privacidade</Link></li></ul></div>
    <div><h2 className="font-bold">Contato</h2><ul className="mt-4 space-y-4 text-sm text-white/70"><li><a className="flex gap-3 hover:text-white" href={`tel:${company.phoneHref}`}><Phone className="size-5 shrink-0 text-solar" />{company.phoneDisplay}</a></li><li><a className="flex gap-3 break-all hover:text-white" href={`mailto:${company.email}`}><Mail className="size-5 shrink-0 text-solar" />{company.email}</a></li><li className="flex gap-3"><MapPin className="size-5 shrink-0 text-solar" /><span>{company.address}<br />{company.serviceArea}</span></li></ul><div className="mt-5 flex gap-3"><a aria-label="Instagram" href={company.socials.instagram}><Instagram /></a><a aria-label="Facebook" href={company.socials.facebook}><Facebook /></a><a aria-label="LinkedIn" href={company.socials.linkedin}><Linkedin /></a></div></div></div>
    <div className="border-t border-white/10"><div className="container-site flex flex-col gap-3 py-6 text-xs text-white/60 sm:flex-row sm:justify-between"><p>© {new Date().getFullYear()} Micronativa. Todos os direitos reservados.</p><p>{company.serviceArea}.</p></div></div>
  </footer>;
}
