"use client";
import Link from "next/link";
import {ArrowLeft,ArrowRight,Check,FileText,LoaderCircle,Paperclip,Trash2} from "lucide-react";
import {useEffect,useMemo,useRef,useState} from "react";
import {useSearchParams} from "next/navigation";
import {serviceOptions,propertyTypes,purposes,contactMethods,acceptedTypes,MAX_FILES,MAX_FILE_SIZE} from "../data/quoteOptions";
import type {QuoteRequest,QuoteService,QuoteAttachment} from "../types/quoteRequest";
import {formatPhone,bytes} from "../utils/format";
import {generateTemporaryProtocol} from "../utils/generateTemporaryProtocol";
import {submitQuoteRequest} from "@/services/quoteRequestService";
import {projects} from "@/data/projects";
import {trackEvent} from "@/lib/analytics";
import {WhatsAppButton} from "@/components/WhatsAppButton";
import {cn} from "@/lib/utils";

const initial:QuoteRequest={service:"",additionalServices:[],propertyType:"",purpose:"",city:"",state:"",projectDetails:{},attachments:[],customer:{name:"",phone:"",whatsapp:"",email:""},preferredContactMethod:"WhatsApp",privacyConsent:false,sourcePage:"direct"};
const labels=Object.fromEntries(serviceOptions.map(x=>[x.value,x.label])) as Record<QuoteService,string>;
const detailQuestions:Record<string,Array<{key:string;label:string;placeholder?:string}>>={
"energia-solar":[{key:"energyBill",label:"Valor m?dio da conta de energia",placeholder:"Ex.: R$ 450"},{key:"electricalConnection",label:"Tipo de liga??o el?trica",placeholder:"Monof?sica, bif?sica ou trif?sica"},{key:"roofArea",label:"?rea aproximada do telhado",placeholder:"Ex.: 60 m?"}],
"cftv-seguranca":[{key:"environments",label:"Quantidade aproximada de ambientes"},{key:"internalArea",label:"?rea interna a monitorar"},{key:"externalArea",label:"?rea externa a monitorar"},{key:"remoteAccess",label:"Acesso pelo celular?"},{key:"recording",label:"Precisa de grava??o?"}],
"automacao-portoes":[{key:"gateType",label:"Tipo de port?o"},{key:"installed",label:"O port?o j? est? instalado?"},{key:"hasMotor",label:"Possui motor atualmente?"},{key:"problem",label:"Problema atual, se houver"}],
"controle-acesso":[{key:"accessCount",label:"Quantidade aproximada de acessos"},{key:"accessType",label:"Tecnologia desejada",placeholder:"Tags, biometria, senha..."},{key:"usage",label:"Tipo de uso"}],
"projeto-integrado":[{key:"priorities",label:"Quais s?o as prioridades do projeto?"},{key:"infrastructure",label:"H? infraestrutura instalada?"},{key:"phase",label:"Deseja executar por etapas?"}],
"manutencao":[{key:"system",label:"Qual sistema precisa de manuten??o?"},{key:"problem",label:"Descreva o problema observado"},{key:"since",label:"Quando o problema come?ou?"}]
};
function fieldClass(error?:string){return cn("input",error&&"border-red-500");}
export function QuoteRequestWizard(){
 const params=useSearchParams();const heading=useRef<HTMLHeadingElement>(null);
 const [step,setStep]=useState(1);const [data,setData]=useState<QuoteRequest>(initial);const [errors,setErrors]=useState<Record<string,string>>({});const [status,setStatus]=useState<"idle"|"loading"|"success"|"error">("idle");const [protocol,setProtocol]=useState("");
 const validService=serviceOptions.some(x=>x.value===params.get("service"))?params.get("service") as QuoteService:"";
 const project=projects.find(p=>p.slug===params.get("project")||p.id===params.get("project"));
 useEffect(()=>{setData(old=>({...old,service:old.service||validService,projectReference:project?.id,sourcePage:["home","service","project","solutions"].includes(params.get("source")??"")?params.get("source")!:"direct"}));trackEvent("quote_form_started",{source:params.get("source")??"direct",service:validService||undefined,projectId:project?.id});},[]);
 useEffect(()=>{heading.current?.focus();setErrors({});},[step]);
 useEffect(()=>{try{const safe={...data,attachments:[]};sessionStorage.setItem("mn-quote-draft",JSON.stringify(safe));}catch{}},[data]);
 const set=<K extends keyof QuoteRequest>(key:K,value:QuoteRequest[K])=>setData(old=>({...old,[key]:value}));
 const customer=(key:keyof QuoteRequest["customer"],value:string)=>setData(old=>({...old,customer:{...old.customer,[key]:value}}));
 const validate=()=>{const e:Record<string,string>={};if(step===1&&!data.service)e.service="Selecione uma solu??o.";if(step===1&&data.service==="projeto-integrado"&&!data.additionalServices.length)e.additional="Selecione ao menos um servi?o para integrar.";if(step===2){if(!data.propertyType)e.propertyType="Selecione o tipo de im?vel.";if(!data.purpose)e.purpose="Selecione a finalidade.";if(data.city.trim().length<2)e.city="Informe a cidade.";if(!/^[A-Za-z]{2}$/.test(data.state))e.state="Use a sigla do estado com 2 letras.";}if(step===5){if(data.customer.name.trim().length<3)e.name="Informe seu nome.";if(data.customer.phone.replace(/\D/g,"").length<10)e.phone="Informe um telefone v?lido.";if(!/^\S+@\S+\.\S+$/.test(data.customer.email))e.email="Informe um e-mail v?lido.";if(!data.privacyConsent)e.consent="O consentimento ? obrigat?rio.";}setErrors(e);return !Object.keys(e).length;};
 const next=()=>{if(!validate())return;trackEvent("quote_form_step_completed",{step,service:data.service,source:data.sourcePage});setStep(s=>Math.min(6,s+1));};
 const addFiles=(list:FileList|null)=>{if(!list)return;const nextFiles:QuoteAttachment[]=[];let message="";for(const file of Array.from(list)){if(!acceptedTypes.includes(file.type)){message="Use somente JPG, PNG, WEBP ou PDF.";continue;}if(file.size>MAX_FILE_SIZE){message="Cada arquivo deve ter no m?ximo 8 MB.";continue;}if(data.attachments.length+nextFiles.length>=MAX_FILES){message="Voc? pode enviar at? 6 arquivos.";break;}nextFiles.push({id:crypto.randomUUID(),name:file.name,size:file.size,type:file.type,file});}if(message)setErrors({files:message});set("attachments",[...data.attachments,...nextFiles]);};
 const submit=async()=>{setStatus("loading");try{await submitQuoteRequest(data);const p=generateTemporaryProtocol();setProtocol(p);setStatus("success");trackEvent("quote_form_submitted",{service:data.service,source:data.sourcePage,projectId:data.projectReference,completionStatus:true});sessionStorage.removeItem("mn-quote-draft");}catch{setStatus("error");}};
 const q=useMemo(()=>detailQuestions[data.service||"manutencao"],[data.service]);
 if(status==="success")return <div className="mx-auto max-w-2xl rounded-4xl border bg-white p-7 text-center shadow-soft sm:p-12"><span className="mx-auto grid size-16 place-items-center rounded-full bg-forest-pale text-forest"><Check className="size-8"/></span><h1 className="mt-6 text-3xl font-bold">Solicita??o enviada com sucesso</h1><p className="mt-4 leading-7 text-muted">Recebemos suas informa??es no adaptador demonstrativo. Conecte o formul?rio a um backend antes de captar solicita??es reais.</p><div className="mx-auto mt-6 max-w-sm rounded-2xl bg-warm p-5"><p className="text-xs font-bold uppercase tracking-wider text-muted">Protocolo tempor?rio</p><p className="mt-2 text-2xl font-extrabold text-navy">{protocol}</p></div><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><WhatsAppButton context="quote" protocol={protocol} service={data.service||undefined} propertyType={data.propertyType||undefined} city={data.city+" - "+data.state} label="Enviar resumo pelo WhatsApp"/><Link href="/" className="btn-secondary">Voltar para o in?cio</Link></div></div>;
 return <div className="mx-auto max-w-4xl">
  {project&&<div className="mb-5 rounded-2xl border border-forest/20 bg-forest-pale p-4 text-sm"><strong>Projeto de refer?ncia:</strong> {project.title}<button className="ml-3 underline" onClick={()=>set("projectReference",undefined)}>Remover refer?ncia</button></div>}
  <div className="mb-6"><div className="flex items-center justify-between text-sm font-bold"><span>Etapa {step} de 6</span><span className="text-muted">{["Solu??o","Im?vel","Detalhes","Anexos","Contato","Revis?o"][step-1]}</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-navy-pale"><div className="h-full bg-forest transition-all" style={{width:(step/6*100)+"%"}}/></div></div>
  <div className="rounded-4xl border bg-white p-5 shadow-soft sm:p-9" aria-live="polite">
   {step===1&&<section><h1 ref={heading} tabIndex={-1} className="text-3xl font-bold">Qual solu??o voc? procura?</h1><p className="mt-2 text-muted">Escolha a necessidade principal para personalizarmos as pr?ximas perguntas.</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{serviceOptions.map(o=><button key={o.value} type="button" aria-pressed={data.service===o.value} onClick={()=>set("service",o.value)} className={cn("min-h-28 rounded-2xl border p-5 text-left transition",data.service===o.value?"border-forest bg-forest-pale ring-2 ring-forest/15":"hover:border-forest/40")}><o.icon className="size-6 text-forest"/><span className="mt-4 block font-bold">{o.label}</span><span className="mt-1 block text-sm text-muted">{o.description}</span></button>)}</div>{errors.service&&<p role="alert" className="mt-3 text-sm font-semibold text-red-700">{errors.service}</p>}{data.service==="projeto-integrado"&&<div className="mt-6"><p className="font-bold">Quais servi?os deseja combinar?</p><div className="mt-3 flex flex-wrap gap-2">{serviceOptions.slice(0,4).map(o=><button key={o.value} type="button" aria-pressed={data.additionalServices.includes(o.value)} onClick={()=>set("additionalServices",data.additionalServices.includes(o.value)?data.additionalServices.filter(x=>x!==o.value):[...data.additionalServices,o.value])} className={cn("min-h-11 rounded-full border px-4 py-2 text-sm font-bold",data.additionalServices.includes(o.value)&&"border-forest bg-forest text-white")}>{o.label}</button>)}</div>{errors.additional&&<p role="alert" className="mt-2 text-sm text-red-700">{errors.additional}</p>}</div>}</section>}
   {step===2&&<section><h1 ref={heading} tabIndex={-1} className="text-3xl font-bold">Conte um pouco sobre o im?vel</h1><div className="mt-7 grid gap-5 sm:grid-cols-2"><label className="font-bold">Tipo de im?vel<select value={data.propertyType} onChange={e=>set("propertyType",e.target.value as any)} className={fieldClass(errors.propertyType)}><option value="">Selecione</option>{propertyTypes.map(x=><option key={x}>{x}</option>)}</select>{errors.propertyType&&<span className="mt-1 block text-sm text-red-700">{errors.propertyType}</span>}</label><label className="font-bold">Finalidade<select value={data.purpose} onChange={e=>set("purpose",e.target.value as any)} className={fieldClass(errors.purpose)}><option value="">Selecione</option>{purposes.map(x=><option key={x}>{x}</option>)}</select>{errors.purpose&&<span className="mt-1 block text-sm text-red-700">{errors.purpose}</span>}</label><label className="font-bold">Cidade<input className={fieldClass(errors.city)} value={data.city} onChange={e=>set("city",e.target.value)} autoComplete="address-level2"/>{errors.city&&<span className="mt-1 block text-sm text-red-700">{errors.city}</span>}</label><label className="font-bold">Estado<input className={fieldClass(errors.state)} value={data.state} maxLength={2} onChange={e=>set("state",e.target.value.toUpperCase().replace(/[^A-Z]/g,""))} placeholder="UF" autoComplete="address-level1"/>{errors.state&&<span className="mt-1 block text-sm text-red-700">{errors.state}</span>}</label></div></section>}
   {step===3&&<section><h1 ref={heading} tabIndex={-1} className="text-3xl font-bold">Quais s?o as necessidades do projeto?</h1><p className="mt-2 text-muted">Responda o que souber. A equipe confirma os detalhes no levantamento t?cnico.</p><div className="mt-7 grid gap-5 sm:grid-cols-2">{q.map(item=><label key={item.key} className="font-bold">{item.label}<input className="input" placeholder={item.placeholder} value={String(data.projectDetails[item.key]??"")} onChange={e=>set("projectDetails",{...data.projectDetails,[item.key]:e.target.value})}/></label>)}<label className="font-bold sm:col-span-2">Observa??es<textarea className="input min-h-32 resize-y" value={String(data.projectDetails.notes??"")} onChange={e=>set("projectDetails",{...data.projectDetails,notes:e.target.value})}/></label></div></section>}
   {step===4&&<section><h1 ref={heading} tabIndex={-1} className="text-3xl font-bold">Deseja enviar imagens ou documentos?</h1><p className="mt-2 text-muted">Opcional. At? 6 arquivos JPG, PNG, WEBP ou PDF, com no m?ximo 8 MB cada. Os arquivos n?o s?o enviados sem backend.</p><label className="mt-7 flex min-h-40 cursor-pointer flex-col items-center justify-center rounded-3xl border-2 border-dashed border-navy/20 bg-warm p-6 text-center hover:border-forest"><Paperclip className="size-8 text-forest"/><span className="mt-3 font-bold">Selecionar arquivos</span><input type="file" multiple accept=".jpg,.jpeg,.png,.webp,.pdf" className="sr-only" onChange={e=>addFiles(e.target.files)}/></label>{errors.files&&<p role="alert" className="mt-3 text-sm text-red-700">{errors.files}</p>}<ul className="mt-5 space-y-2">{data.attachments.map(file=><li key={file.id} className="flex items-center gap-3 rounded-2xl border p-4"><FileText className="size-5 text-forest"/><span className="min-w-0 flex-1"><strong className="block truncate text-sm">{file.name}</strong><span className="text-xs text-muted">{bytes(file.size)} ? aguardando integra??o</span></span><button type="button" onClick={()=>set("attachments",data.attachments.filter(x=>x.id!==file.id))} className="grid size-11 place-items-center rounded-full hover:bg-red-50" aria-label={"Remover "+file.name}><Trash2 className="size-5"/></button></li>)}</ul></section>}
   {step===5&&<section><h1 ref={heading} tabIndex={-1} className="text-3xl font-bold">Como podemos entrar em contato?</h1><div className="mt-7 grid gap-5 sm:grid-cols-2"><label className="font-bold">Nome<input className={fieldClass(errors.name)} value={data.customer.name} onChange={e=>customer("name",e.target.value)} autoComplete="name"/></label><label className="font-bold">Telefone<input type="tel" inputMode="tel" className={fieldClass(errors.phone)} value={data.customer.phone} onChange={e=>customer("phone",formatPhone(e.target.value))} autoComplete="tel"/></label><label className="font-bold">WhatsApp<input type="tel" inputMode="tel" className="input" value={data.customer.whatsapp} onChange={e=>customer("whatsapp",formatPhone(e.target.value))} autoComplete="tel"/></label><label className="font-bold">E-mail<input type="email" className={fieldClass(errors.email)} value={data.customer.email} onChange={e=>customer("email",e.target.value)} autoComplete="email"/></label></div><fieldset className="mt-6"><legend className="font-bold">Forma de contato preferida</legend><div className="mt-3 flex flex-wrap gap-2">{contactMethods.map(x=><label key={x} className={cn("flex min-h-11 cursor-pointer items-center gap-2 rounded-full border px-4",data.preferredContactMethod===x&&"border-forest bg-forest-pale")}><input type="radio" name="contact" checked={data.preferredContactMethod===x} onChange={()=>set("preferredContactMethod",x)}/>{x}</label>)}</div></fieldset><label className="mt-7 flex items-start gap-3 rounded-2xl bg-warm p-4"><input type="checkbox" checked={data.privacyConsent} onChange={e=>set("privacyConsent",e.target.checked)} className="mt-1 size-5"/><span className="text-sm leading-6">Autorizo o uso dos meus dados para atendimento desta solicita??o, conforme a <Link href="/politica-de-privacidade" className="font-bold text-forest underline">Pol?tica de Privacidade</Link>.</span></label>{errors.consent&&<p role="alert" className="mt-2 text-sm text-red-700">{errors.consent}</p>}</section>}
   {step===6&&<section><h1 ref={heading} tabIndex={-1} className="text-3xl font-bold">Revise sua solicita??o</h1><p className="mt-2 text-muted">Voc? pode voltar a qualquer etapa sem perder os dados.</p><div className="mt-7 grid gap-4 md:grid-cols-2">{[["Solu??o",data.service?labels[data.service]:"?",1],["Im?vel",data.propertyType+" ? "+data.purpose,2],["Local",data.city+" ? "+data.state,2],["Detalhes",Object.values(data.projectDetails).filter(Boolean).join(" ? ")||"Sem detalhes adicionais",3],["Anexos",data.attachments.length+" arquivo(s)",4],["Contato",data.customer.name+" ? "+data.preferredContactMethod,5]].map(([t,v,s])=><div key={t as string} className="rounded-2xl bg-warm p-5"><div className="flex items-center justify-between"><h2 className="font-bold">{t as string}</h2><button type="button" className="text-sm font-bold text-forest underline" onClick={()=>setStep(s as number)}>Editar</button></div><p className="mt-2 break-words text-sm leading-6 text-muted">{v as string}</p></div>)}</div>{status==="error"&&<p role="alert" className="mt-5 rounded-xl bg-red-50 p-4 text-sm font-bold text-red-700">N?o foi poss?vel enviar. Revise os dados e tente novamente.</p>}<div className="mt-6 rounded-2xl border border-solar/50 bg-solar/10 p-4 text-sm leading-6"><strong>Importante:</strong> nesta vers?o, o envio usa um adaptador demonstrativo e n?o armazena dados permanentemente. Conecte um backend antes da capta??o real.</div></section>}
   <div className="mt-9 flex flex-col-reverse gap-3 border-t pt-6 sm:flex-row sm:justify-between">{step>1?<button type="button" onClick={()=>setStep(s=>s-1)} className="btn-secondary"><ArrowLeft className="size-4"/>Voltar</button>:<span/>}{step<6?<button type="button" onClick={next} className="btn-primary">Continuar <ArrowRight className="size-4"/></button>:<button type="button" onClick={submit} disabled={status==="loading"} className="btn-primary disabled:opacity-60">{status==="loading"?<><LoaderCircle className="size-4 animate-spin"/>Enviando</>:<>Enviar solicita??o <ArrowRight className="size-4"/></>}</button>}</div>
  </div>
 </div>;
}
